export const queryKeys = {
  employees: "employees",
  singleemployee: "singleemployee",
  departments: "departments",
  designations: "designations",
  institutes: "institutes",
  allowances: "allowances",
  deductions: "deductions",
  experiences: "experiences",
  educations: "educations",
  leaves: "leaves",
  expenses: "expenses",
  expenses_payrun: "expenses_payrun",
  payslips: "payslips",
  payrun: "payrun",
  trainings: "trainings",
  family: "family",
  dailyallows: "dailyallowances",
  dailyallowsdetls: "dailyallowsdetls",
  user: "user",
  currency: "currency",
};
